export {
  computeBME,
  characterBME,
  getMDC,
  setMDC,
  getEatCost,
  getBatheCost,
  getVitalBaseRate,
  dailyVitalDecay,
  getTierMultiplier,
  getTierDailyIncome,
  getTierInitialMoney,
  getMoodDecayRate,
  getMoodVolatilityPerTick,
  getSocialDecayPerTick,
  getSocialGainPerDialogTick,
  getSicknessBaseDuration,
} from "@agw/systems";
